language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2.101
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true 
  - DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - dotnet build ./src/lib/Xdal.Abstractions/Xdal.Abstractions.csproj
  - dotnet build ./src/lib/Xdal.EntityFrameworkCore/Xdal.EntityFrameworkCore.csproj
  - dotnet build ./src/lib/Xdal.EntityFrameworkCore.InMemory/Xdal.EntityFrameworkCore.InMemory.csproj
  - dotnet build ./src/lib/Xdal.EntityFrameworkCore.SQLite/Xdal.EntityFrameworkCore.Sqlite.csproj
  - dotnet build ./src/lib/Xdal.EntityFrameworkCore.SqlServer/Xdal.EntityFrameworkCore.SqlServer.csproj
